---
version: '3'
services:
  slicer:
    image: stevepieper/slicer
    environment:
      - containerName="slicer"
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./htpasswd:/etc/nginx/conf/htpasswd
    restart: always
